version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      all-pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/generators/angular/generator"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      all-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "generators/angular/generated-examples"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
