version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/generators/angular/generator"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "generators/angular/generated-examples"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 10
