site_name: OpenUI Specification
site_description: Documentation for the OpenUI specification.
repo_url: https://github.com/shlomoa/openui5-spec
theme:
  name: readthedocs
docs_dir: spec
nav:
  - Overview: README.md
